export const charactors = [
    {
        id:1,
        width: 800,
        height:1067,
        url:"/charactorimg/aromatic.jpg",
        alt:"Aromatic",
        header:"Aromatic",
    },{
        id:2,
        width: 800,
        height:1067,
        url:"/charactorimg/revitalising.jpg",
        alt:"Revitalising",
        header:"Revitalising",
    },{
        id:3,
        width: 800,
        height:1067,
        url:"/charactorimg/natural.jpg",
        alt:"Natural",
        header:"Natural",
    },{
        id:4,
        width: 800,
        height:1067,
        url:"/charactorimg/aquatic.jpg",
        alt:"Aquatic",
        header:"Aquatic",
    },{
        id:5,
        width: 800,
        height:1067,
        url:"/charactorimg/mediterranean.jpg",
        alt:"Mediterranean",
        header:"Mediterranean",
    },{
        id:6,
        width: 800,
        height:1067,
        url:"/charactorimg/descreet.jpg",
        alt:"Descreet",
        header:"Descreet",
    },{
        id:7,
        width: 800,
        height:1067,
        url:"/charactorimg/bouquet.jpg",
        alt:"Bouquet",
        header:"Bouquet",
    },{
        id:8,
        width: 800,
        height:1067,
        url:"/charactorimg/oriental.jpg",
        alt:"Oriental",
        header:"Oriental",
    },{
        id:9,
        width: 800,
        height:1067,
        url:"/charactorimg/classical.jpg",
        alt:"Classical",
        header:"Classical",
    },{
        id:10,
        width: 800,
        height:1067,
        url:"/charactorimg/noble-timber.jpg",
        alt:"Noble timber",
        header:"Noble timber",
    },{
        id:11,
        width: 800,
        height:1067,
        url:"/charactorimg/woody.jpg",
        alt:"Woody",
        header:"Woody",
    },{
        id:12,
        width: 800,
        height:1067,
        url:"/charactorimg/spicy.jpg",
        alt:"Spicy",
        header:"Spicy",
    },{
        id:12,
        width: 800,
        height:1067,
        url:"/charactorimg/smoky.jpg",
        alt:"Smoky",
        header:"Smoky",
    },{
        id:13,
        width: 800,
        height:1067,
        url:"/charactorimg/citric.jpg",
        alt:"Citric",
        header:"Citric",
    }
]